# Generated by Django 5.1.3 on 2024-11-16 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_customuser_otp_customuser_otp_expiry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
