# Generated by Django 5.1.3 on 2024-11-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
