# Generated by Django 5.1.3 on 2024-11-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0005_alter_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='kitchen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/gallery_images/'),
        ),
    ]
