# Generated by Django 5.1.3 on 2024-11-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0006_property_bathroom_property_kitchen_property_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
