# Generated by Django 5.1.3 on 2024-11-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0007_property_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathroom',
        ),
        migrations.RemoveField(
            model_name='property',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rooms',
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='bathroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='kitchen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
